### ISSUE TITLE
플랫폼 이주(?) 건의

### ISSUE THREAD

**Issue by jhtwosun** [skullbe/Kaiserreich-Korean-Translation#104]
아무래도 용어를 정하는 문제가 많을것 같은데, 

Glossary(단어장) 기능이나 Transition memory(비슷한 번역문 보여주기?) 등이 있는 Zanata에서 진행하는 것이 더 좋지 않을까요? (다른 역설사 게임 번역들도 진행되고 있기도 하고요.)

**Comment by skullbe** [comment]
일단 zanata사이트가 사이트인지라 초기설정이 복잡한데다가 접근성도 깃허브가 더쉬워서 이 문장이라도 번역하고 싶다하면 쉽게 쉽게 할 수 있으니 지금으로선 옮길필요가 없다고 생각합니다
