### ISSUE TITLE
번역 도움 요청

### ISSUE THREAD

**Issue by muelleri** [skullbe/Kaiserreich-Korean-Translation#106]
미국 내전 부분 번역 중인데 한 부분에서 막혀서 도움 구하고자 올려봅니다

The end of the Civil War had brought with it the uncertainty as to what needs to be done with the country. Some of the Pacific States leadership wished to keep control of the entire country, but the majority felt that the PSA should reinstate the Union throughout the east and keep the PSA separate.

미국 내전 끝나고 미 태평양 합중국이 미합중국과 어떻게 해야할지 고르는 이벤트입니다.  
우선 첫번째 문장은 자연스럽게 번역하기가 어렵더라구요.  
두번째 문장은 쉽긴 한데 마지막의 keep the PSA separate 가 뭘 의미하는지 햇갈려서 문제입니다.
(PSA 지도부의 일부는 전국을 지배하길 원했지만, 다수는 PSA가 동쪽의 연방에 복귀해야 한다고 생각했고 .....) 
PSA의 분리 독립을 유지한다는 건지.... PSA를 분열시켰다는 건지 햇갈리네요. 

그래서 일단 도움 요청해봅니다.
글은 답변이 올라오면 후에 삭제하겠습니다.

**Comment by jeongSoyu** [comment]
내전은 종식되었지만 점령 지역을 손볼 방안에 관한 설왕설래가 남아있습니다.
태평양 합중국의 지도층 일부는 전 지역을 통제 아래에 두기를 바라는 눈치지만, 태평양 합중국을 동부에 건재한 연방의 품으로 복귀시키되 자치를 하도록 분리 상태를 유지하자는 것이 대다수의 의견입니다.

...라고, 감히 제안을 해보겠습니다.

**Comment by muelleri** [comment]
흠 우선은 비슷한 식으로 번역해보겠습니다.
