### ISSUE TITLE
Communes 번역에 관해

### ISSUE THREAD

**Issue by skullbe** [skullbe/Kaiserreich-Korean-Translation#11]
국가명에 Communes이 붙은게 많은데요, 이걸 '코뮌 독일'이런식으로 해야할지

뜻 그대로 '독일 공동체'라고 해야할지 의역으로 '독일 사회주의 공화국' 이런식으로 번역할지

정하고 번역을 해야될 것같습니다. 다들 의견은 어떠신가요?

**Comment by qq97890** [comment]
흠..... 그냥 번역 하는 1인으로써는 그냥 굳이 번역하기 보다는 코뮌이라는 말 자체를 쓰는게 더 나을거 같아보입니다.

**Comment by hitohabune** [comment]
파리 코뮌처럼 고유명사로 가야한다고 봅니다.

**Comment by hitohabune** [comment]
파리 코뮌의 선례가 있으니 프랑스 코뮌, 독일 코뮌처럼 가야죠

**Comment by hitohabune** [comment]
파리 코뮌의 선례가 있으니 프랑스 코뮌, 독일 코뮌처럼 가야죠

**Comment by hitohabune** [comment]
파리 코뮌의 선례가 있으니 프랑스 코뮌, 독일 코뮌처럼 가야죠

**Comment by skullbe** [comment]
그럼 코뮌으로 번역하도록 하겠습니다
