### ISSUE TITLE
Flanders-Wallonia는 플랑드르-왈로니아에서 플란데런-우알로니로 변경된거 아니었나요?

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#1539]
안내사항에
"Flanders-Wallonia는 기존합의로 플랑드르-왈로니아로 합의되었음에도, 일괄변경이 없었지만, 5월11일 업데이트와 동시에 이뤄질 계획입니다."
라 쓰였는데 플란데런-우알로니로 번역을 통일한건 어찌된건가요? 갑자기 예전 번역을 사용할려는 이유가 있는건가요?

**Comment by skullbe** [comment]
카라 0.8.4 업데이트부터 원어표기와 영문식표기에 대해 분명히 하기위해 미틀아프리카 처럼 원어표기가 유지된 것들은 그대로 가고, 독일령 동아시아나 동아시아 회사같은 경우는 원어표기에서 영문식 표기로 변경되었습니다.

Flanders-Wallonia는 독일괴뢰국이여서, 원어표기로 바뀔줄 알았으나, 변경이 없어서 원본모드에 따르고자 영문식 표기로 변경한 것입니다. 

플란데런-우알로니를 로마자로 옮기면,
네덜란드어식 표기와 프랑스어식 표기가 섞여서 'Vlaanderen-Wallonie' 이렇게 됩니다.
Flanders-Wallonia랑은 괴리감이 커서, 추후 번역에 참가하시는 분들로 하여금 다시 논쟁이 될 수도 있어서 이같이 결정했습니다.
