### ISSUE TITLE
헝가리인 인명에 대해

### ISSUE THREAD

**Issue by khg2202** [skullbe/Kaiserreich-Korean-Translation#177]
헝가리인 인명은 성 이름 순서 인 걸로 아는데 영어 원문에는 이름 성 순으로 쓰여있습니다.
예를 들어 István Bethlen은 이슈트반 베틀렌이라고 번역하는게 나을까요 아니면 베틀렌 이슈트반이라고 번역하는게 나을까요

**Comment by friangang** [comment]
개인적으로는 후자쪽이 좋아보인다고 생각합니다.

**Comment by Kaiserwangguk** [comment]
헝가리 전통을 따르는게 낫다고 봅니다.

**Comment by khg2202** [comment]
그럼 후자로 하겠습니다
