### ISSUE TITLE
AOG의 번역어에 관한 제안

### ISSUE THREAD

**Issue by mirachbeta** [skullbe/Kaiserreich-Korean-Translation#1816]
번역을 해본 적은 없는 지나가던 사람입니다. 

AOG가 **일반 동아시아 회사**로 번역되어있는데, 이게 직관적으로 와닿지 않습니다. 
원문은 **Allgemeine Ostasiatische-Gesellschaft**이니까 낱말 단위로 직역하면 일반 동아시아 회사가 맞는데, 현실세계에서 그런 비슷한 용법은 쓰이질 않죠. 

AOG를 봤을 때 가장 먼저 연상되는 회사는 **AEG**입니다. 원문은 **Allgemeine Elektricitäts-Gesellschaft**이고, 한국어 위키백과에서는 '일반전기회사'로 번역되어 있습니다. AEG는 에밀 라테나우라는 유대계 독일인 기업가가 에디슨의 발명품을 보고 만든 회사이며, 처음 만들었을 때 Deutsche Edison-Gesellschaft für angewandte Elektrizität(독일 응용전기 에디슨 회사)라는 이름이었던 것을 AEG로 바꾼 겁니다. 그리고 우리는 에디슨이 세운 회사인 GE, **General Electric**을 알고 있죠. 영어로 General은 독일어의 Allgemeine와 거의 1:1 매칭이 되는 단어입니다. 콜린스 영어사전에도 Allgemeine를 찾으면 General이 가장 먼저 나오고 그 아래에 Public이나 Universal 등이 나옵니다. 

GE의 경우, 에디슨이 갖고 있던 사업체 4개를 합쳐서 만든 Edison General Electric Company가 전신입니다. 당시까지 에디슨이 갖고 있던 사업체들의 이름은 각각 Edison Lamp Company, Edison Machine Works, Bergmann & Company, Edison Electric Light Company입니다. '에디슨 무슨 회사'들을 하나로 합쳐서 GE를 만들었기 때문에, 자연스럽게 제너럴 일렉트릭은 **에디슨 일반 전기 회사**가 아니라 **에디슨 종합 전기 회사**라는 의미임을 알 수 있습니다. 전기와 관련된 것은 무엇이든 하는 회사라는 뜻입니다. 

따라서, 저는 AOG를 **종합 동아시아 회사, 동아시아 종합회사, 동아시아 종합상사** 등으로 번역하는 것을 제안합니다. 

AOG의 Allgemeine를 '일반'으로 번역할 경우, AOG가 정확하게 어떤 형태의 회사인지 쉽게 와닿기 어렵습니다. '일반'을 국어사전에서 찾아보면 '특별하지 아니하고 평범한 수준. 또는 그런 사람들.'이라는 뜻으로, 어디에서나 흔히 볼 수 있고 별로 특별하지 않다는 어감이 강합니다. 
하지만 '종합'으로 번역할 경우, 우리가 흔히 '종합상사'라고 하면 알 수 있듯이 뭐든 가리지 않고 닥치는대로 사고 파는 중개업자, 거대한 만물상 같은 이미지임을 직관적으로 떠올릴 수 있습니다. 이뿐만 아니라 종합상사 특유의 거대재벌 이미지가 맞물리면서, **독일어로 된 이질적인 느낌의 거대재벌이 남중국을 점유하는 현실에 저항하며 봉기하는 중국 국민당**이라는 이미지가 보다 효과적으로 전달될 수 있을 것입니다. 

번역에 힘써주시는 모든 분들께 감사를 표합니다.

**Comment by MikMikMr** [comment]
동아시아 종합상사에 찬성합니다.

**Comment by salamander724** [comment]
종합상사는 일본식 표현이니 독일 사명을 옮기는 데는 합당하지 않은 것 같고 "종합 동아시아 회사" 에 한표 하겠습니다.

**Comment by skullbe** [comment]
현재 최신버전에서는 'Aufsichtsrat der Ostasiatische Generalverwaltung'으로 약칭이 변경되어 
일단은 '동아시아 총괄행정 감사회'로 사용 중인데, 다른 의견이 있으신지요?

**Comment by mirachbeta** [comment]
확인이 늦었습니다. 최근 중국 지역 대격변이 진행되더니 AOG도 바뀌어버렸나보네요... 

Generalverwaltung은 영어로 직역하면 General administration인데, 여기에서 general은 '종합'이나 '총괄' 같은 어감보다는 '일반'의 어감에 더 가까워보입니다. 쉽게 말하면 '자치부' 같은 곳에서 하는 일이란 뜻이죠. '내무부'라고 하기에는... 내무부는 보통 경찰기관이나 방첩조직 같은 국가안보 분야에서 더 존재감을 드러내는 경우가 많아서, 그런 쪽보다는 정말로 일반적인 행정, 그러니까 친근한 동네 동사무소 아저씨들 같은 느낌이네요. 
그러니까 Generalverwaltung은 일반행정에 가깝습니다...만은 이것도 단순하지 않은 문제죠. 여기까지는 AOG가 '통치기관'에 더 가까울 때의 얘기입니다. 만약 AOG가 '사기업'에 더 가깝다면, '일반행정'보다는 '총괄경영'의 어감에 더 가까울 수 있습니다. 제가 위키를 읽어본 바에 따르면 AOG의 통제권이 '이사회'에게 있고, 앞에 붙는 Aufsichtsrat도 감안해서 '총괄경영'이 맞지 않을까 싶습니다만... 카라 설정에 대한 이해력이 높으신 다른 분들께서 잘 판단해주실 것 같습니다. administration을 행정으로 하겠다면 '일반행정'이 될 것이고, 경영으로 하겠다면 '총괄경영'이 되겠죠. 

Aufsichtsrat를 감사회로 번역하는 것에는 별다른 이견이 없습니다. 다만 약간만 더 욕심을 내자면, 한국에서는 영미식 경영 시스템에 더 익숙하기 때문에 단순히 '감사회'라고만 해놓으면 이사회 옆에 독립적으로 딸려있는 감사 전문 조직으로만 생각할 수 있는데, 독일식 경영 시스템에서는 Aufsichtsrat가 이사회보다 상위에 있는 사실상의 최고결정기구에 가깝습니다. 비유하자면 주주총회와 직원총회의 상임위원회 같은 역할을 하죠. 이러한 점을 감안해서 '감독이사회' 정도로 번역하는 경우가 종종 보이더라구요. 

종합하자면, '동아시아 총괄경영 감독이사회'나 '동아시아 일반행정 감독이사회' 정도가 어떨까 합니다.

**Comment by salamander724** [comment]
영어의 General 은 "총- / 일반-"의 뜻이 있지만, 독일어에서 "일반-"이라고 하려면 Allgemeine 가 되어야 합니다. 그래서 과거 Allgemeine Ostasien Gesellschaft 가 "일반 동아시아 회사"였던 것이구요. 독일어 표현이 General 로 바뀌었다면 "총괄"이 "일반"보다 타당해 보입니다. 

Verwaltung  는 영어로 authority 에 해당하는데, 이건 보통 공기업에 사용되는 표현으로서 한국어로는 "ㅇㅇ공사"라고 할 수 있습니다. 

Aufsichtsrat 는 독일 경영에서 Vorstand 와 대조되는 것으로, 후자가 경영을 맡는 이사회라면 전자는 그 활동을 감독하는 감사들로 이루어진 기구입니다. 

종합적으로 아우프지히츠라트 데어 오슈타지아티셰 게네랄페르발퉁 Aufsichtsrat der Ostasiatische Generalverwaltung 은 "**동아시아 총괄공사 감사이사회**"  라고 옮기는 것이 타당해 보입니다.

**Comment by mirachbeta** [comment]
카라 위키에서는 AOG의 영어 번역을 Supervisory Board of the East Asian General Administration으로 하고 있습니다. Authority가 아니라 Administration을 의도하고 있다면 공사가 들어갈 이유가 없을 듯합니다. 
Supervisory Board이니까 감사이사회는 남기고, 기업에서 주로 사용하는 용어임이 분명하니까 General Administration도 총괄경영이 더 좋을 것 같습니다.

**Comment by skullbe** [comment]
그러면 '동아시아 총괄경영 감사이사회'로 명칭변경 하도록 하겠습니다.
