### ISSUE TITLE
미국 국명에 대한 번역명 재고 토론

### ISSUE THREAD

**Issue by skullbe** [skullbe/Kaiserreich-Korean-Translation#1858]
새로 오셔서 번역하시는분들이 번역을 헷갈리게 해놓은 것도 수정하고, 현재도 중구난방인 경우가 몇몇 있어서 한번에 통일시킬겸 다시한번 토론을 열어보게 되었습니다.

초창기에 한번 했었고, 그때는 DHR 번역을 따르기로 결정하여 

American Union State : 미주연합
Combined Syndicates of America : 아메리카 노동 연맹
Pacific States of America :미 태평양 합중국

이렇게 결정됬었습니다. 

이때는 Federated States of America, United Provinces of America, Confederate States of America 등등도
있던 시절이다보니 그대로 갔었지만, 지금은 셋으로 줄어들었으니, 조금씩 차이나게 번역할 필요도 없게  됬습니다.

아시다시피 CSA나 PSA는 과거에 합의된대로 번역하기에는 원문과 의미차이가 큽니다. 
United Pacific States of America가 아닌데 태평양 합중국일 필요는 없습니다.  Combined Syndicates 역시 뜻이 노동연맹보다는 노조연합에 가깝지 않을까요? 
여기서 Syndicate가 Trade Union이랑 같은 뜻으로 사용한거라고 봅니다. 

그리고 영어 원문도 그랬듯이, USA랑 운을 같게 해서 번역할 때도 운을 같거나 비슷하게 하면 더 좋을듯합니다. 
그래서 다음과 같은 제안을 해봅니다.

American Union State: 미연합국, 미연방국
Combined Syndicates of America: 미연합조합, 미노조연합, 미합노조, 미합조합
Pacific States of America: 미태평양국

**Comment by EngineerBeans** [comment]
유저들이 번역에 가진 불만 중 하나가 '아메리카'와 '미' 라는 표기가 반복된다는 점도 있었던걸로 아는데 저 역시 의견에 동의하여 모두 '미'로 표기했으면 좋을 듯 합니다

**Comment by EngineerBeans** [comment]
일단 State를 ~주로 변경할지 ~국으로 변경할지를 정하는게 우선이라고 생각됩니다

**Comment by MikMikMr** [comment]
Pacific States of America는 '미국 태평양 주 연합'이나 그냥 '미 태평양 주' 이런식이 나을것 같습니다

**Comment by EngineerBeans** [comment]
States를 주로 표기 하는건 아닌거 같습니다. 당장 사빈코프의 러시아도 러시아국, 영어로 Russian State이고 현실 일본의 국명인 일본국도 영어로  State of Japan이므로 States는 국으로 표현하는게 옳다 봅니다.

**Comment by EngineerBeans** [comment]
이번에 CSA를 미합조합으로 번역하셨던데 저는 미노조연합 쪽이 훨씬 낫다고 생각됩니다.

1. 미합조합 같은 경우 처음 보면 당최 뭔 국명인가 싶을 정도로 이전 번역이던 아메리카 노동 연맹과는 괴리감이 큽니다

2. 미연합국은 남부연합처럼 연방 정부에 대응해, 미태평양국은 태평양에서 연방 정부에 대응해 일어난 느낌을 쉽게 알 수 있지만 미합조합이라는 국명으로는 성향이나 일어난 이유를 알 수가 없습니다.

따라서 저는 이전 번역에서 많이 바뀌면서도 수정이 가해진 미노조연합으로 재번역 할 것을 제안하고 싶습니다

**Comment by skullbe** [comment]
알겠습니다. 그럼 미노조연합으로 반영하도록 하겠습니다

**Comment by MikMikMr** [comment]
'States'는 복수형이므로 당연히 '주'들을 의미한다고 봐야지요. '미 태평양 국가들'은 아니니까요. 원문인 'Pacific States of America'부터가 기존의 미국에서 떨어져나간 태평양 주들을 지칭하는 것 아닌가요? 직역하면 '미국(America)의 태평양 주들'이 되는데 이걸 '미태평양국'으로 번역하는 것은 부적절하다고 봅니다. 차라리 미국 정통성을 주장하는 태평양 정부라는 의미를 전달하기 위해 '태평양 미합중국'이나 '미 태평양 주 연합'등을 제안해 봅니다.

**Comment by EngineerBeans** [comment]
태평양 미합중국은 저도 괜찮은거 같습니다 유저들 의견도 이쪽이 인기가 많은거 같기도 하고요

**Comment by qq97890** [comment]
지나친 원문만 강조한 번역입니다. 실제적으로 이 번역을 보게 될 한국인들이 어떻게 보느냐가 더 중요하다고 봅니다. 

차라리 과거 번역으로 회귀하는걸 원하지만 그게 안된다면....

CSA:미국 노조연합, USA:미국, PSA:태평양 미국. AUS:미국 연방으로 번역하는게 나을거 같습니다. 전부 미국의 정통성을 주장하는 세력이니 미국을 명시하고, 추가적으로 원문을 참고해서 수식어를 붙이는 방식으로 말이죠.

**Comment by skullbe** [comment]
일단 종합적인 의견 수렴으로,

CSA: 미국 노조연합
PSA: 태평양 미합중국
으로 하려고 합니다.

AUS의 경우, 연방단어를 사용하고 싶긴한데, Federal Government를 연방정부로 사용하고 있어서 헷갈릴 수 있기 때문에  '연합미국'으로 사용하고자 하는데 이에대한 의견은 어떠신가요?

**Comment by EngineerBeans** [comment]
USA: 미합중국
CSA: 미국 노조연합
AUS: 미연합국/미연방국
PSA: 태평양 미합중국

이렇게 제안합니다

일단 저는 '연합 미국'/'연방 미국'은 반대하는게 딱봐도 AUS 모티브가 남부연합인데 굳이 ~ 미국이라는 번역을 쓸 이유는 없이 또다른 미국이란 느낌을 주는 것도 좋을거 같습니다
물론 남부연합의 공식국명인 미연합국의 영문명이 'Confederate States of America'이다 보니 미연방국이 좀 더 맞겠지만요

일단 솔직히 저는 이전 번역들이 뜻이라면 몰라도 의향이나 전달력에 있어서는 좋았다고 생각해 재번역에 좀 회의적입니다. 말씀하신대로 연방 정부와 미연방국이 연방으로 공통되다보니 '미주연합'이라는 기존 번역에서 '미주'라는 약자 표현으로 구분이 쉽게 되었으니까요
