### ISSUE TITLE
Fagoppositions Sammensluting 번역명

### ISSUE THREAD

**Issue by khg2202** [skullbe/Kaiserreich-Korean-Translation#1988]
기존 번역은 노동조합인데 이게 고유명사인지 일반명사인지 헷갈릴 때가 있습니다.
그래서 다른 단어를 쓰려는데 좋은 거 없을까요.

없으면 '노조 야권 연합' 정도로 하겠습니다.

**Comment by kawaialpaca** [comment]
영어로는 Trade Oppositions Association 으로 번역된다고 하니 그렇게 번역하는게 옳을 것으로 보입니다
