### ISSUE TITLE
처음 기여를 해보고 싶은 사람인데, 번역에 참가할 수 있는건가요?

### ISSUE THREAD

**Issue by bgh1234554** [skullbe/Kaiserreich-Korean-Translation#2105]
대학교 1학년 학생입니다. 학교에서 오픈소스소프트웨어 기초 과제로 커뮤니티 체험 보고서? 같은걸 적어오라는데, 그래서 기여같은걸 해보고 싶은데, 어디다가 적어야 할지 몰라서.. 여기에 적어봅니다...

**Comment by skullbe** [comment]
https://github.com/skullbe/Kaiserreich-Korean-Translation/blob/Translator/README.md
여기에 나오신대로 진행하시면 됩니다.
