### ISSUE TITLE
미국 잭 리드 당선 설명문 번역에 관해서 도움을 받고 싶습니다.

### ISSUE THREAD

**Issue by Portuguneia** [skullbe/Kaiserreich-Korean-Translation#212]
Against even the Combined Syndicates' wildest hopes, Jack Reed has been elected as the 31st president of the United States. His victory shocks not just America but the whole world. The syndicalists and their allies are jubilant at his success, while shouts of Red Traitor erupt throughout the country from those in the centre and the right galvanising them already against him. This most unexpected outcome seems to be setting the US on the path of gradual democratic socialism, that is if they can avoid any conflicts.

미국 노조 연맹의 격렬한 열망을 배경으로,잭 리드는 미국의 31대 대통령으로 선출되었습니다. 그의 승리는 미국 뿐만 아니라 전세계를 충격에 빠트렸습니다.권력의 중심에서부터 나라 도처로 "빨갱이"들의 외침은 뻗어나가고 있고,조합주의자들과 그들의 동맹은 그의 성공에 의기양양하고 있는 동안 벌써 리드에 반대하는 세력이 행동을 취하고 있는중입니다. 이 가장 예상치 못한 결과는 미국을 점진적인 사회민주주의의 길로 이끌어갈것으로 보입니다. 만일 그들이 어떠한 충돌도 겪지 않는다면 말이죠. 

라고 해석을 했지만 The syndicalists~against him. 까지의 문장을 어떻게 해석할지 난감합니다. 제가 의역을 너무 많이 섞어서 의미전달이 안될지도 모를것 같아서 여쭈어 봅니다.

**Comment by Little-Mans** [comment]
조합주의자들과 그들의 동맹은- 에서 은-을 들이- 로 바꾸는게 나을 것 같네요, 
저 "Red Traitor" 부분이 가장 난해한 부분이겠네요, 이게 CSA를 뜻하는지 CSA와 대적하는 사람들이 말하는 것인지를 모르니까...

**Comment by Portuguneia** [comment]
아무래도 리드가 당선이 됬으니 그동안 쌓인 노동조합원들의 분노가 터진다 그거 뉘앙스인거 같긴한데...진짜 저 Red traitor가 뭔지 모르겠네요 그냥 빨갱이라고 지칭하는 단어로 보기엔 너무 난해해요 ㅋㅋ....

**Comment by skullbe** [comment]
약간 부정적으로 서술된듯해요 리드와 반대되는 정통세력들이 빨갱이라고 보는 입장으로.. 부드럽게 하기 위해선 생디칼리스트로 번역하는 것도 괜찮을 것같습니다

**Comment by kgu4244** [comment]
회색분자로 표기하면 어떨까요
