### ISSUE TITLE
중국쪽 번역 관련 질문입니다

### ISSUE THREAD

**Issue by spacedove** [skullbe/Kaiserreich-Korean-Translation#2188]
봉천 정부에서 Reclamation war 가 계속 나오는데

이걸 뭐라고 해석해야 하나요? 재수복 재통일 중국 통일...

그리고 지역이나 인명도 영어로 써진 원문 그대로 적어야 할지 아니면 좀 이름있는 도시같은 경우엔 한자 이름으로 써야할지 랴오둥 반도 요동 반도나 동북 3성 둥베이 3성등등 옌시산인지 염석산인지..

**Comment by skullbe** [comment]
국명은 한자독음으로, 그 외에는 전부 원어독음으로 합니다.
Yunnan Clique의 경우, 운남 군벌로 번역하지만, Yunnan 지역명을 가르킬 때는 윈난으로요.
인물명 역시 원어독음로 표기합니다.
동북 3성이나 요동 반도도 각각 둥베이 3성, 랴오둥 반도로 표기하는 것이 좋을 것같습니다.

**Comment by MikMikMr** [comment]
저는 Reclamation war는 수복전쟁으로 번역했습니다.

**Comment by spacedove** [comment]
답변 감사합니다!
