### ISSUE TITLE
텍스트 내에서 직접 이벤트에 연동되는 부분이 있는지, 한글이 인식되는지 궁금합니다.

### ISSUE THREAD

**Issue by kor-eagle** [skullbe/Kaiserreich-Korean-Translation#2215]
HOI의 경우 이벤트 메세지에 텍스트로 표시되는 부분과 실제 명령어가 따로 있어서 "" 내의 수정에는 걱정할 일이 없는건 알지만, 혹시 예외사항이 있는지 확인차 질문합니다.

텍스트 내에 단순히 글자만 있는게 아니라 \n이나 색입히기 등 이런저런 명령어가 들어가있는데, [] 괄호로 된 부분을 제외하고 혹시 조심해야할 부분이 있는지 궁금합니다. 

또한 []를 제외하고 ()괄호나 단순 색입히기 등의 경우, 그 안에 한글을 사용해도 문제없이 인식이 되는지도 확인하고 싶습니다. 
ex. "(Consumer Goods Factories: §Y5%§!)" -> "(소비재 공장: §Y5%§!)"

**Comment by skullbe** [comment]
[GetPOPLEVEL] 이런게 아니면 상관없습니다. 소비재 공장 부분은 맞게 번역하셨습니다. 보통 변수들은 눈에 띄게 되있습니다. Factor_level과 같이 '_' 기호혹은 []괄호 안에 있는것만 주의하셔서 번역하시면 됩니다.
