### ISSUE TITLE
"바라티야 코뮌"에 대해서

### ISSUE THREAD

**Issue by asukalovesmisato** [skullbe/Kaiserreich-Korean-Translation#2382]
"바라티야"는 "바라트"의 형용사형인데 ( 바라티야 : 바라트 :: 코리안 : 코리아 ) "바라트 코뮌"이라고 해야 타당한 것 아닐까요? Finnish Republic 을 핀란드 공화국이라고 하지 피니시 공화국이라고는 안 하듯이요. 마찬가지로 European Union 도 유럽연합이지 유러피언 연합은 아니죠.

**Comment by gyhs** [comment]
카라 제작총괄 Zankoas의 답변에 따르면, '인도(India)'라는 명칭은 인더스에서 유래하였으나 코뮌은 인더스를 소유하지 않았기 때문에 인도라는 이름을 사용하지 않았다고 하며, 대신 힌디를 음차한 '바라티야'를 택했다고 함. 엄밀히 따지면 '바라티야'는 '바라트의'를 의미하는 형용사이므로 '바라트 코뮌'이라 할 수도 있겠으나, 원어 표기에 대한 형평성 문제, "바라티야"를 굳이 사용하고 싶었던 카이저라이히 팀의 의도, 그리고 사다리 타기를 통한 결정에 따라 '바라티야'가 최종 확정되었습니다
