### ISSUE TITLE
단어 사전보고 의문점 및 이상한 점 적습니다.

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#2384]
라이히스팍트
협상국을 엔테테라고 하지 않듯이 굳이 원어 발음으로 쓸 이유가 없을듯 합니다? 비슷한 예시로 우리가 유럽 연합을 원어 발음으로 부르지는 않으니까요

브랑겔
이전부터 계속 말한건데 브랑겔은 독일어 발음 브란겔이 러시아어 발음 입니다 게임상 브란겔은 러시아인인데 왜 계속 독일식 발음으로 바꾸려드는지 모르겠습니다

pact
협약으로 할지 조약으로 할지 통일성이 필요합니다.

**Comment by vdnkh1** [comment]
Warsaw Pact 가 바르샤바 조약기구이듯 베오그라드 '조약'이 더 적절한것 같습니다.
라이히스팍트도 기존의 제국조약이 더 적절한것 같구요.

**Comment by gyhs** [comment]
1. 라이히스팍트 - 라이히스팍트는 유럽연합의 경우처럼 확정된 번역어가 존재하지 않습니다. 또한 제국조약 등의 번역어는 공동체로서의 의미를 훼손하며 그러므로 더 나은 번역이 존재하지 않는 한 음역이 답이라고 생각했습니다. 그리고 유럽 연합은 따지면 공용어 16개에 동등한 연합체인데 카이저라이히에서의 라이히스팍트는 독일의 지위가 압도적이며, 독일어 Reich가 제국이라는 뜻을 가진게 아닙니다. (현대에는 Kaiserreich가 제국) 만일 또다른 예시로 Deutsches Reich라는 단어를 사용하신다면, Deutsches Reich는 독일 제국 뿐만 아니라 바이마르 공화국, 나치독일 역시 이 단어를 사용하였으며, 국가판무관부(Reichskommissariat) 역시 Reich가 포함되지만 국가로 번역되는게 정확하다는 점을 들어 Reich라는 단어에서 제국이라는 뜻을 찾기보다는 오히려 국가라는 뜻을 찾는 것이 빠를 것이라고 생각됩니다. 또한, Reichspakt라는 단어를 사용한 카이저라이히 팀의 의도를 비추어볼때 역시 위에서 말했듯이 독일의 압도적인 지위를 상징하는 것이라고 결론이 나왔습니다.

2. 브랑겔 - 브란겔로 해놨습니다.

3. Pact - 협약으로 진행하겠습니다. (외교부 공식 번역)

4. 위에서 협약이 외교부의 번역을 따른 것이므로 Belgrad 'Pact' 역시 협약으로 수정하겠습니다.

**Comment by Rope-player** [comment]
국가간 동맹을 맺는 상황에서는 윗 분 말대로 '바르샤바조약'처럼 조약이 더 적절할 것 같습니다.

**Comment by gyhs** [comment]
국가간의 동맹이라면 서로의 협력을 약속하는 행위입니다. 그러므로 협약이라는 단어가 더 가까운 단어라고 생각합니다. 바르샤바 조약기구나 북대서양 조약기구 같은 용어는 "일본어" 번역문을 그대로 한국어로 가져오는 경우에서 만들어진 말이므로 예시에 걸맞지 않습니다.

**Comment by gyhs** [comment]
https://ja.wikipedia.org/wiki/%E5%8C%97%E5%A4%A7%E8%A5%BF%E6%B4%8B%E6%9D%A1%E7%B4%84%E6%A9%9F%E6%A7%8B
일본어로 "북대서양 조약기구"라고 적혀있는 것을 확인하실수 있으실 것입니다.

https://zh.wikipedia.org/wiki/%E5%8C%97%E5%A4%A7%E8%A5%BF%E6%B4%8B%E5%85%AC%E7%BA%A6%E7%BB%84%E7%BB%87
하지만 중국어에서는 "북대서양공약조직"으로  서로 번역어가 다릅니다. 그러므로 어차피 번역을 할 것이라면 대한민국 외교부가 사용하는 협약을 사용하기로 결정했습니다.
