### ISSUE TITLE
Deutsch-Mittelafrika 번역에 관해

### ISSUE THREAD

**Issue by jeongSoyu** [skullbe/Kaiserreich-Korean-Translation#24]
작중 독일 제국의 식민지 국가로 등장하는 Deutsch-Mittelafrika의 국명을 어떻게 번역할지, 번역자분들의 의견을 여쭙고 싶습니다.

1. 완전히 발음대로 (**도이치 미텔아프리카**)
2. 부분적으로 발음대로 (**독일령 미텔아프리카**)
3. 의미대로 (**독일령 중앙아프리카**)

**Comment by skullbe** [comment]
의미대로 독일령 중앙아프리카가 좋을 것같습니다. 중앙아프리카 식민지를 뜻하니, 굳이 원어 그대로 읽기보다 의미대로 쓰는게 좋을 것같아요

**Comment by jhtwosun** [comment]
그러면 MittelEuropa를 어떻게 할까요? 일단은 '미텔유로파' 라고 번역해놨습니다만...

**Comment by hitohabune** [comment]
3번이 괜찮을 것 같습니다.
우리가 지금 영어를 준공용어로 쓴다 해도 중동을 미들 이스트라고 하지 않는 것처럼 카라 세계관은 독일이 패권을 잡은 상태라 중앙아프리카를 미텔아프리카로 부르는 것 뿐이라고 봅니다. 의미가 같고 명확하게 대체할 수 있는 고유어가 있다면 바꿔야한다고 봅니다.

**Comment by hitohabune** [comment]
Comintern처럼 고유어라면 코민테른으로 번역해야겠지만 Allies를 연합국, Axis를 추축국으로 번역한 선례가 있으니 미텔오이로파보다는 중부유럽이라고 번역하는 게 좋을 것 같습니다.

**Comment by jeongSoyu** [comment]
Mittelafrika : 중앙아프리카 (**합의완료**)
Mitteleuropa : 중부유럽, 중앙유럽.

또는 중앙유럽공동체? 이건 너무 나갔나요.

**Comment by jhtwosun** [comment]
중부 유럽보다는 중앙(부) 유럽 연합이 덜 어색하지 않을까요?
