### ISSUE TITLE
다음 패치 변경사항 관련

### ISSUE THREAD

**Issue by gyhs** [skullbe/Kaiserreich-Korean-Translation#2461]
1. 다음 패치에서 변경사항을 적어주셨으면 하시는 분은 이곳 아래에 적어주시기 바랍니다. 
(한번 적어주신분은 그걸 계속 수정해주세요!)
2. 카이저라이히 번역용 디코나 카페를 개설하시면 들어오실분 있으신가요?
(요즘 바빠져서 검수를 제대로 못하는점 죄송합니다!)

**Comment by attatuirk** [comment]
카페라면 어느 포털에 개설할 생각이신가요

**Comment by gyhs** [comment]
네이버 쪽을 생각하고 있습니다.

**Comment by attatuirk** [comment]
> 네이버 쪽을 생각하고 있습니다.

번역용어 선정 외에도 여러 면에서 단순히 깃허브에서만 말하는것보다는 편할듯 하니 들어가는게 좋겠네요

**Comment by gyhs** [comment]
만약 디스코드로 한다면 친목 방지를 위해서 모든 닉네임을 ㅇㅇ으로 통일할 생각입니다.
또한, 카이저라이히 번역 외의 채팅방은 개설하지 않겠습니다.
