### ISSUE TITLE
센트로아메리카 번역해둔 부분이 다 날아갔습니다

### ISSUE THREAD

**Issue by attatuirk** [skullbe/Kaiserreich-Korean-Translation#2619]
KR_Centroamerica_flavour_l_english.yml 파일과 KR_Centroamerica_Soc_l_english.yml 파일, 그리고 KR_Centroamerica_flavour_l_english.yml 파일 번역분이 사라졌습니다. 뭐 어쩔 수 없는 건가요?

**Comment by gyhs** [comment]
파일 합치면서 다 날아간듯한데... 제가 프로그램으로 합친게 화근이었나 보네요...
죄송합니다

**Comment by denev3510** [comment]
0.10.1 버전 백업해논게 있어서 한글부분 내용 복붙해서 올렸습니다

**Comment by denev3510** [comment]
KR_Centroamerica_Soc_l_english.yml 랑 KR_Central_America_l_english.yml은 파일이 있어 올렸는데, flavor 파일은 없어서 올리지 못했습니다...

**Comment by attatuirk** [comment]
그렇군요

**Comment by attatuirk** [comment]
전에는 파일명이 달랐었는데, 혹시 그것때문이었나요?

**Comment by denev3510** [comment]
창작마당에 있던 1월에 끊긴 구 한패과 비교해 보았을 때, 중앙아메리카 파일은 KR_Central_America_l_english.yml, KR_Centroamerica_Soc_l_english.yml만 확인된 점으로 미루어보아 이 두 개의 파일 외 의 나머지 파일은 새로 추가된 것으로 보입니다. 제가 재업한 파일은 캐나다 업데이트 직전의 것 일부를 마침 들고 있어서 업로드 하였습니다.

**Comment by attatuirk** [comment]
제가 번역을 올렸을 때에는 파일명이 Centroamerica 가 아니라 CA였었습니다. KR_CA_flavour_l_english.yml 파일이 있는지 확인 부탁드립니다.

**Comment by denev3510** [comment]
지금 확인해보니 KR_CA_Military_l_english.yml, KR_CA_Democracy_l_english.yml, KR_CA_flavour_l_english.yml 파일이 있는걸 확인했습니다. 다만 Military 파일 제외하고선 민주주의쪽은 "중앙아메리카 민주주의 중점계도"라는 이름 한줄만 번역이 되어있고, flavour파일에는 한줄도 번역된 것이 없어 군부 번역된 부분만 따로 업로드 했습니다.

**Comment by denev3510** [comment]
중앙아메리카 민주주의쪽은 제가 어제 이 토론 보기 전에 번역한게 많아서.. 한번 훑어보시고 당명이라던가 그런게 안맞는게 있다 싶으시면 보시고 수정하시면 됩니다.
