### ISSUE TITLE
번역 관련 질문입니다.

### ISSUE THREAD

**Issue by LaFayette319** [skullbe/Kaiserreich-Korean-Translation#2635]
제가 최근 번역에 합류하여 관련하여 지침이 있었는지는 모르겠습니다만, 번역 파일 중간에 가끔씩 나오는 회색 부분도 번역을 해야 하나요? 파일에만 있고 게임에 실제로는 언급이 안되나 싶어 여쭤봅니다.

**Comment by gyhs** [comment]
혹시 앞에 #이 붙어있나요? 그렇다면 굳이 안하셔도 됩니다. #은 뒤의 구문을 무시한다는 뜻입니다.

**Comment by LaFayette319** [comment]
아 그렇군요, 답변 감사합니다.
