### ISSUE TITLE
번역에 참여해주셔서 정말 감사합니다.

### ISSUE THREAD

**Issue by gyhs** [skullbe/Kaiserreich-Korean-Translation#2678]
다만 호환작업이 진행되고 있을때는 번역하셨던게 롤백될수 있으니 주의해주시기 바랍니다. 감사합니다.

**Comment by vdnkh1** [comment]
수고하십니다. 호환작업은 전부 마무리된 것인가요?

**Comment by gyhs** [comment]
> 수고하십니다. 호환작업은 전부 마무리된 것인가요?

넵!
