### ISSUE TITLE
특정 팩션명 (미텔아프리카 , 미텔에우로파) 번역 제안

### ISSUE THREAD

**Issue by friangang** [skullbe/Kaiserreich-Korean-Translation#294]
이전에 협의된 사항중 하나이지만,  그중에  'Mitteleuropa'가 '중부 유럽' , 'Mittelafrica'가 '중앙아프리카' 로 번역되는 것은 적절치 않다고 생각합니다. 미텔에우로파 팩션을 말하는 건지 말그대로 유럽의 중부 지역을 말하는 건지 혼동의 여지가 있습니다. 후자쪽도 마찬가지입니다. 확실히 팩션의 명칭인 것을 알 수 있도록 번역을 개선하거나, 차라리 해당 팩션명 한정으로라도 음차해서 번역하는 쪽이 개인적이지만 낫다고 보아 다시 이의제기합니다. 다른 분들 의견이 궁금합니다.

**Comment by khg2202** [comment]
찬성합니다.
미틀오이로파, 미틀아프리카 정도면 괜찮을거 같네요.
