### ISSUE TITLE
디시전 번역 중... 

### ISSUE THREAD

**Issue by esswibi** [skullbe/Kaiserreich-Korean-Translation#355]
Let us use 'ingenious diplomacy' to bring Persia into the fold.

이 것을 번역할 때, in to the fold 부분 일대를 어떻게 해석하는 것이 좋을까요?

"Now that the Alash state have been dealt with we can strike at the heart of the Islamic state of Turkestan. Their long list of crimes is about to come to an end."

이 내용에서도 Their long list of crimes을 무엇으로 번역하는 것이 좋을 지 궁금합니다.

**Comment by friangang** [comment]
'into the fold' 에서 'fold'는 [감싸다]라는 뜻이지만 해당 문장에서는 [우리 영역] 또는 [우리 편]이라는 의미로 사용되었습니다. 의미를 반영해서 "'영리한 외교'로 페르시아를 우리 편으로 끌어들입시다." 가 적당해 보입니다.

후자는 직역하면 [그들의 긴 범죄 목록]이며 문맥상 앞의 문장과 연결하면
"이제 알라쉬를 처리했으니 우리는 튀르키스탄 이슬람국의 심장부를 공격할 수 있습니다. 그들의 오랜 죄악은 곧 마침표를 찍게 될 것입니다."
가 적절해 보여 번역을 제안해 봅니다.

**Comment by esswibi** [comment]
좋은 번역 도움 감사드립니다.
