### ISSUE TITLE
soviet에 대한 번역

### ISSUE THREAD

**Issue by esswibi** [skullbe/Kaiserreich-Korean-Translation#367]
소련 번역도중 'Soviet'라고만 나오는 경우를 일단 소비에트라고 번역을 했는데, 우선 소련이라고 번역하자니  부하린 이외의 다른 루트를 타면 국명이 '소비에트 러시아'나 '소비에트 공화국'이 되는지라 그렇게 했습니다만, 이것이 잘못된 번역 같나요?

**Comment by skullbe** [comment]
괜찮다고 봅니다. Britain같은거면 상황에 따라 달라지겠지만, Soviet는 소비에트로 불러도 상관이 없으니까요
