### ISSUE TITLE
소련 번역의 반영에 대해서...

### ISSUE THREAD

**Issue by esswibi** [skullbe/Kaiserreich-Korean-Translation#373]
소련 디시전들을 번역했는데, 그것이 적용됬나 인게임에서 확인해봤는데도 불구하고 디시전 내용이 번역이 안된 상태로 있습니다. Pull request도 거쳤고 번역한 뒤 업데이트가 있었던것같았는데도 여전했던게 좀 이상합니다.

**Comment by skullbe** [comment]
아직 번역본을 업데이트하지 않아서 그렇습니다. 번역승인직후 바로 업데이트하는게 아니라 일주일마다 끊어서 하고 있습니다.
