### ISSUE TITLE
intergration of 부분 번역에 대해서...

### ISSUE THREAD

**Issue by esswibi** [skullbe/Kaiserreich-Korean-Translation#378]
소련 해외 이벤트 번역 도중 'intergration of'로 시작되는, 특정 국가를 합병해 그곳의 주를 핵심주로 만드는듯한 내용이 있는데, 그걸 번역할 때 제목으로 뜨는 'intergration of **'는 '**의 통합'하고 '**의 합병'중 어떤 것이 더 자연스러워 보이나요? 

그리고, 이 이벤트 내용에서 다른 분이 한국, 만주의 'The areas of the former state of ** are now firmly integrated into our growing socialist motherland.'부분을 벌써 번역하신 것 같은데 다른 국가의 그 부분도 이미 번역된 그 내용을 바탕으로 하는 것이 좋을까요, 아니면 새로 번역하는 것이 좋을까요?

**Comment by khg2202** [comment]
합병은 Annexation의 번역으로 두고 integration은 통합으로 하는게 나을거 같네요

번역된 내용 바탕이 좋겠죠
