### ISSUE TITLE
Reichspakt 명칭번역 문제

### ISSUE THREAD

**Issue by skullbe** [skullbe/Kaiserreich-Korean-Translation#401]
이번 업데이트로 중앙유럽동맹이 Reichspakt로 변경이 되었는데,

명칭문제를 확실히 하고 가야 할 것같습니다.

제국 동맹, 제국 조약등등 다양하게 번역이 가능하니까요

**Comment by khg2202** [comment]
원문 그대로 읽는 건 어떨까요
라이히스팍트

**Comment by DanmooZi** [comment]
제국 협정이나 1차대전의 동맹국을 그대로 쓰는게 어떨까 싶네요.

**Comment by khg2202** [comment]
그러면 제국 협정으로 하죠
