### ISSUE TITLE
공사관 도시 변역질문

### ISSUE THREAD

**Issue by Southkoreaball** [skullbe/Kaiserreich-Korean-Translation#430]
포커스 트리중에 The Night of the Monkey's Head 라는게 있는데요. 번역하기가 애매합니다. 어떻게 번역해야 항까요?

**Comment by Little-Mans** [comment]
직역하면 원숭이 머리의 밤인데 원숭이 머리를 한자로 바꾸면 될것같네요 
후두? 두후? 그쯤이면 되겠죠?
