### ISSUE TITLE
카이저라이히 개발팀과 연락문제는 어떻게 되었나요?

### ISSUE THREAD

**Issue by kawaialpaca** [skullbe/Kaiserreich-Korean-Translation#505]
https://www.reddit.com/r/Kaiserreich/comments/8oa0ud/kaiserreich_recruitment_update/

이쪽 링크를 들어가보시면 아시겠지만 한국어 팀과 연락을 했지만 아직 응답이 없다고 하네요. 어떤식으로든지 답장해서 연계를 취하는 쪽이 좀더 도움이 되지 않을까요??

**Comment by skullbe** [comment]
예전에 어떤분이 연락을 취했다고 하셨었는데 그거였나보네요. 일단 Zankoas 스팀으로 개인 메세지 보냈습니다
