### ISSUE TITLE
카이저라이히 번역중 Soviet 부분에 대한 의견입니다. 

### ISSUE THREAD

**Issue by esswibi** [skullbe/Kaiserreich-Korean-Translation#535]
제가 카이저라이히 Soviet의 내셔널 포커스들의 제목과 설명내용을 한글로 번역했고, 그것이 Pull request등을 거쳐 0.6 업데이트 되었다고 했는데도 불구하고 여전히 영어로 나온것 같습니다. 왜 그렇게 나오는 것인지 궁금합니다.

**Comment by skullbe** [comment]
승인이 되었다고 해서, 곧 바로 모드가 창작마당에서 업데이트가 되는 것은 아닙니다. 아마 현재는 일본쪽까지만 반영이 되있을거에요. 곧 모든 파일에 대한 호환작업을 끝낸후 업데이트할 계획입니다.
