### ISSUE TITLE
flanders, wallonia의 번역어

### ISSUE THREAD

**Issue by khg2202** [skullbe/Kaiserreich-Korean-Translation#578]
flanders, wallonia의 번역이 자꾸 바뀌고 있어서 말해봅니다.
원문이 flanders-wallonia고 카이저라이히 위키에는 풀네임이 Flandern-Wallonien (Flanders-Wallonia)로 나와있으니 플랑드르-왈로니아 (영어) 또는 플란던-발로니엔(독일어)이 가장 맞지 않나요?

**Comment by skullbe** [comment]
저는 독일어표기를 찬성합니다. 독일속국으로 나오는입장이니, 독일어표기가 더 좋을 것같아요. 
근데 독일어 발음시에 플란던보다는, 플란데언이나 플란드언에 더 가깝지 않나요?

**Comment by khg2202** [comment]
발음이 [ˈflandɐn]니깐 모음은 한글자가 맞을거 같습니다.

**Comment by kawaialpaca** [comment]
아예 원어를 살려서 플란데런-우알로니로 하는 방법은 어떤가요? 앞부분은 네덜란드어로 플란데런으로 발음하고 뒷부분은 프랑스어로 우알로니로 발음해서...

**Comment by kawaialpaca** [comment]
하긴 생각해보니 영어로 하는쪽이 편하긴 할것 같네요 독일어로 하면 헷갈릴 수도 있으니...

**Comment by EngineerBeans** [comment]
현재 국명이 플란데런-우알로니로 되어있는데 이게 오역인건가요 아니면 이 국명으로 통일하기로 결정한건가요?

**Comment by kawaialpaca** [comment]
엥 제가 전에 직접 플랑드르-왈로니아로 바꿨는데 누가 롤백했나본데요....

**Comment by EngineerBeans** [comment]
그러면 플랑드르-왈로니아 고치겠습니다
