### ISSUE TITLE
누군가가 네셔널 표퓰리즘을 단순히 표퓰리즘으로 번역 했는데......

### ISSUE THREAD

**Issue by qq9789** [skullbe/Kaiserreich-Korean-Translation#582]
표퓰리즘이 극우의 전유물도 아닌데, 네셔널 표퓰리즘의 어떤 정치 사상에서도 다 가질 수 있는 표퓰리즘이라고 번역한 것은 무리가 있어 보입니다. 적어도 국가나 민족이라는 단어는 들어가야 해요. 국가(민족) 대중주의/국가(민족) 인민주의 그것도 아니면 국가(민족) 표퓰리즘. 이래야지 적어도 극우적 민족주의에 의존하는 표퓰리즘적 정치인 카라의 네셔널 표퓰리즘 사상을 표현할 수 있다고 봅니다.

따라서 표퓰리즘 단어를 다시 국가대중주의나 혹은 다른 단어로 바꿔야 한다고 봅니다.

**Comment by andwel** [comment]
민족중심주의 이게 어떨까요?

**Comment by andwel** [comment]
국가보다는 민족이 낫지 않을까요. National이라는 게 정치적 단어로 이용될 시에는 민족이라는 용어로 많이 사용되니까요. Nationalism의 경우에도 국가주의가 아니라 민족주의라고 번역이 되니까요

**Comment by qq9789** [comment]
그러면 민족 대중주의로 수정하겠습니다. 이의 없나요?
