### ISSUE TITLE
Landstorm

### ISSUE THREAD

**Issue by andwel** [skullbe/Kaiserreich-Korean-Translation#586]
스웨덴 번역하다가 Landstorm이라는 게 나와서 구글링을 해보니 생소한 편제라 의역했습니다.

위키 설명을 봤을 때 일정 나이대의 미징집된 남성에 대하여 간단한 복장을 지급하고 무장을 시키고 훈련하는 데 관련 사진을 보니 예비군보다는 민병대에 가까운 상태라 '동원민병대'라고 의역을 했습니다.

예비군과 민병대의 중간 형태이고 국가징집이라 의역을 했습니다. 해당 부분에 다른 좋은 단어 있으시면 추천 부탁드립니다.

**Comment by kawaialpaca** [comment]
스웨덴어는 아니지만 독일어로 landstrum 이라고 쳐보니까 국민군이라고 번역된다고 하네요

**Comment by andwel** [comment]
아 네 감사합니다. 국민군으로 수정해야겠네요
