### ISSUE TITLE
정당 번역에 관하여.

### ISSUE THREAD

**Issue by sangchi** [skullbe/Kaiserreich-Korean-Translation#61]
안녕하세요. 정당 이름 관련 번역을 하려 하는데, 몇가지 기준을 정해야 할 것이 있어 이슈에 올려봅니다.
1. 약자의 경우에도 번역을 해야 할까요? 그럼 어떤 형태로 번역을 해야할까요?
- 독일 사민당의 경우 약자는 SPD일겁니다. 그럼 독일 사회민주당으로 번역해야 할까요? 독일 사민당으로 번역해야 할까요? 아니면 사민당으로 번역을 해야 할까요? 아니면 SPD로 그냥 놓아두어야 할까요?
2. 정당 이름이 해당 국가의 언어일 경우엔 어떡해야 할까요?
- 예를 들면 아일랜드의 정당들중 피너 게일 (Fine Gael), 피어너 팔 (Fianna Fáil) 같은 당들 말이지요. 발음 나는대로 적어야 할까요? 아님 이것들을 의역을 해야 할까요?
3. 이 모드에 있을지 모르겠는데, 사람 이름에서 따온 세력 이름, 예를 들면 카를리스타(Carlista)같은 단어는 어떻게 번역을 해야 할까요? 카를리스타? 카를주의자?

(추가) 일단, 번역 기준을 말씀드리자면 위키백과 한국어판에 그 정당의 문서가 있는 경우엔 위키백과의 번역을 따르려 합니다.

(추가 질문) Syndicalist나 생디칼리즘을 노조주의로 번역하셨던데, 그냥 생디칼리스트와 생디칼리즘으로으로 소리나는대로 쓰는게 더 낫지 않을까요? ( 참고 : https://ko.wikipedia.org/wiki/%EC%83%9D%EB%94%94%EC%B9%BC%EB%A6%AC%EC%8A%B4 )

**Comment by qq97890** [comment]
저의 입장을 표명하면......

1.약자는 약자 그대로 쓰는게 좋을것 같습니다. SPD면 다행인데, CSA(미국 사회주의 진영)나 AFU(미국 국가인민주의 진영) 같은 익숙하지 않은 약자의 경우에는 오해를 살 여지가 크다고 생각합니다.

2.역시 개인적 생각이지만 만약 다른 뜻이 있다면 그 뜻으로 쓰거나, 아니면 발음 나는대로 적는게 나아보일듯 합니다.

3.프랑스 코뮌을 번역할때 소렐주의, 소렐주의자라는 단어를 생각하면, 카를주의자처럼 번역하는게 일관성 있지 않을까 생각 합니다.

4.저도 생디칼리즘이라는 단어를 쓰는걸 일단 동의 합니다.

**Comment by sangchi** [comment]
1번의 경우에는 일단 한글로 된 정식 이름을 다 쓰는것 같네요. 그래야할까 생각중입니다.
원래 시스템 상으론 Sozialdemokratische Partei Deutschlands 같이 긴 정식 명칭을 줄여서 나타낼때 쓰는 것 같은데. 한글로는 글자길이가 길진 않을테니까요.

**Comment by qq97890** [comment]
sangchi/그러면 csa나 cnt같은 고유 약자들은 번역하기가 힘들어지는데...

**Comment by sangchi** [comment]
제가 말씀드린 "약자"는 이벤트 내부의 정당 약자가 아닙니다.
국가 코드_정치성향_party:0 "내용" 여기에 들어가는 부분을 이야기 하는 겁니다.
국가 코드_정치성향_party_long:0 "내용" 여기서는 정식 이름을 다 나타내고요.

**Comment by qq97890** [comment]
아 그런거라면... 괜찮은거 같습니다.
