### ISSUE TITLE
0.9 버전에서 중국 쪽에 업데이트가 있을 예정인데 그전에 확실히 해야할 것 같습니다.

### ISSUE THREAD

**Issue by kawaialpaca** [skullbe/Kaiserreich-Korean-Translation#615]
인명, 지명 등의 번역의 표기를 어떻게 정하는 쪽이 나을까요?

예를 들면 Mao Zedong 은 표기를 그대로 쓰면 중국어로의 발음은 마오쩌둥이고 한국식 독음은 모택동입니다. 

현재의 한패 내부에서도 표기법이 확실하지 않기에 통일을 할 필요가 있다고 생각합니다. 

1. 중국어 발음으로 읽은 예 : 쓰촨, 산둥, 윈난 

2. 한국식 독음으로 읽은 예 : 서북삼마, 봉천, 상청천국

**Comment by andares1018** [comment]
한때 봉천을 펑톈으로 해석했었긴 했지만 지금와서 생각해보면 국명에 대해선 한국식 독음으로 하는게 낫다고 생각이 듭니다요.

다만 인명에 대해서는 중국어 발음을 기준으로 잡는게 좋을 것 같습니다.

**Comment by skullbe** [comment]
현재도 그렇듯이, 국명만 한국독음으로 처리하고, 그외에 지역명, 도시명, 사람 이름 등등은 중국발음으로 적는게 좋을 것같습니다.

**Comment by EngineerBeans** [comment]
윈난 군벌 역시 한국식 국명인 운남으로 수정하는게 나을듯 합니다

**Comment by kawaialpaca** [comment]
결론: 지명, 인명에서는 중국어 발음을 사용하되 국명에 있어서는 한국어 독음 사용, 지명에서 국명을 차용한 나라의 경우에도 국명은 한국어 독음으로 

결론은 낫지만 0.9 패치까지는 열어놓도록 하겠습니다
