### ISSUE TITLE
정당의 줄임 외국어를 꼭 쓸 필요가 있을까란 의문이 듭니다

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#627]
말 그대로 현재 영어로 줄여져 있는 정당명을 한국어로 표기하는게 낫지 않을까 합니다
타국가로 상대 국가의 집권 정당을 살필시 정당명이 현재 외국어 줄임말로 나오는데(예로 독일에서 사민당 집권시 SPD라 뜸) 영어의 경우 긴 정당명 때문에 줄임말을 쓰는 것이지만 한국어로는 굳이 별로 길지도 않은 정당명을 영어 약칭으로 해두는 건 좀 이상하다는 생각이 들어 수정하면 좋겠다는 생각이 듭니다 그 예시로 Deutsche Konservative Partei라는 정당은 외국어로는 길어서 약칭 DKP를 쓰지만 한국어로 독일 보수당이라고 간결히 쓸 수 있으니 말이죠

**Comment by skullbe** [comment]
영어표기는 인터페이스를 벗어나는 문제가 있지만, 한국어는 그대로 독음하지 않는 이상 그럴일은 없으니 의견에 동감합니다.

**Comment by EngineerBeans** [comment]
그러면 정당 모두 한글화 하겠습니다
