### ISSUE TITLE
일본 부분 번역에서 국가보안법을 어떻게 처리할까요

### ISSUE THREAD

**Issue by vnv222** [skullbe/Kaiserreich-Korean-Translation#653]
설명 부분을 보니 1925년에 제정된 치안유지법(治安維持法)을 지칭하는 것 같습니다만.. 마이너한 법이라면 그러려니 하고 넘어가고 싶습니다만, 워낙 유명한 법이라서 안고치고 넘어가기도 그러네요.

**Comment by wintersheart** [comment]
일본 파트가 오역이 좀 많습니다. 치안유지법이 올바른 번역입니다.

**Comment by khg2202** [comment]
만약 치안유지법이면 원문이 peace preservation act나 security preservation act 비스무리 해야됩니다만 원문은 national security act여서 다른 이름인게 나을거 같습니다.(법안 내용은 비슷하더라도요)
