### ISSUE TITLE
사빈코프의 지위명과  First Party의 번역을 통일 시켜야 할거 같습니다

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#679]
현재 사빈코프가 러시아 최고 권력자가 되면 vozhd란 지위로 불리는데 이에 대한 번역이 총통,보즈드,영도자,지도자등 통일성 없이 난잡되고 있어 정확한 명칭을 정해야 할 것 같습니다 또한 이와 비슷하게  First Party 역시 우선당,제일당등 두개의 표현이 쓰이고 있어 이에 대한 정확한 명칭 역시 필요해보이고요

일단 제 의견은 vozhd는 영도자로, First Party는 호이2 때 America First Party가 미국 제일당으로 불려 "~제일당" 으로 표기 하는게 가장 좋을듯 하지만 다른 의견이 있을 수도 있으니 이슈를 열겠습니다

**Comment by kawaialpaca** [comment]
제 생각에는 고유 명사라고 생각하고 보즈드는 원음 그대로 쓰는 쪽이 더 나을것 같습니다. First Party 의 경우 제일당에 동의합니다

**Comment by wintersheart** [comment]
보통 퓌러를 원음 그대로 쓰기보다는 총통이라고 번역하는 것처럼 보즈드도 영도자로 번역해서 통일해야 한다고 생각합니다.
 First party도 우선당보다는 제일당이 더 나은 것 같군요

**Comment by EngineerBeans** [comment]
그러면 vozhd는 영도자로 First Party는 제일당으로 번역하겠습니다
