### ISSUE TITLE
일부 국가명에 대하여

### ISSUE THREAD

**Issue by skullbe** [skullbe/Kaiserreich-Korean-Translation#74]
Pacific States of America
Combined Syndicates of America
Centroamerica

이 국가들의 명칭이 그냥 번역하기에는 다양하게 번역이 될 수 있어서 정확히 정해야할 것같습니다.
centroamerica는 아이에 직역하면 중앙아메리카인데 그냥 써야되나 싶기도 하구요

**Comment by muelleri** [comment]
이외에 
Federated States of America (캐나다가 만든 미국 괴뢰국가)
American Union State
United Provinces of America (Socialist Provinces of America) (중앙아메리카 국가)
등도 확실히 해야할 것 같습니다

America가 공통적으로 들어가는데, 미국에서 갈라진 국가들은 국가명에 미국을 포함시키고 이외에 중미쪽은 아메리카를 넣는게 어떨까요

**Comment by skullbe** [comment]
그건 또 애매한 것이 아메리카 연합국입니다 Confederate states of america..

**Comment by sangchi** [comment]
제안)
Pacific States of America : 미 태평양주
Combined Syndicates of America : 미국 노조(노동) 연합(연합체, 연맹, 연맹체)
Centroamerica : 센트로아메리카 (혹은 중미연방)
Federated States of America (캐나다가 만든 미국 괴뢰국가) : 미주연방
American Union State : 미 연방국(?)
United Provinces of America (Socialist Provinces of America) : 아메리카 연합주
Confederate States of America : 아메리카 연합국
미라고 쓰여진걸 아메리카로 바꾸셔도 무방할 것 같습니다.

**Comment by jhtwosun** [comment]
dhr 버젼 번역본에 보면 

- American Union State : 미주연합

- Combined Syndicates of America : 아메리카 노동 연맹

- Pacific States of America : (아메리카) 태평양 합중국

이라 번역되었습니다. 굳이 따를 필요는 없지만, 이미 몇개의 번역이 이렇게 작성되었습니다...

**Comment by IchGrapemon** [comment]
고유 명사표나 번역 방침이 있어야 하지 하지 않을까요. 해당 국가에서만 사용되는 단어면 크게 문제는 없을 것 같은데, 겹치면 문제가 생길 것 같습니다. 그리고 가급적 음차는 지양하고 완역을 하려고 하는데 국가, 정당, 단체, 조직 명칭을 볼 때마다 고민이 되더라구요. 아래 같은 식으로 번역은 했는데,  그러니 음차랑 완역이 중구난방으로 섞여서 난잡해지네요. 그렇다고 다 완역으로 하자니 좀 주저되더라구요. 예를 들어, 루프트바페 같은 걸 그냥 공군으로 번역해버리면 그 느낌이 사라져버리는 것 같아서 고민입니다.

원어: 번역어 // 음차 혹은 완역

국가의 경우는 
  Princely Federation: 번왕 연합
  Union of Britain: 브리튼 연방

진영은 
  Mitteleuropa: 미텔오이로파 // 중부 유럽
  Kaiserbund: 황제 연방  // 카이저분트

군은
  Kaiserliche Marine: 카이저리헤 마리네, 황제 해군
  Seebataillon: 해상대대 // 제바탈리온
  Fliegertruppe: 플리거트루페 // 항공대
  Luftwaffe: 루프트바페 // 공군
  Luftlandetruppe: 루프트란드트루페 // 공수부대
  Bombergruppen: 봄버그루펜 // 폭격기 전대
  Europabrigaden: 유럽 여단 // 오이오파브리가던
  Afrikakorps: 아프리카 군단 // 아프리카코어

장비는
  Sturzflieger: 슈투츠플리거 // 급강하 비행기

정부 조직은
  Verdeckte Reichspolizei: 비밀 제국 경찰 // 퍼덱트 라이히폴리차이
  Reichsarbeitsdienst: 제국 노동 봉사단 // 라이히스아르바이츠딘스트
  Paderborner Luftkriegsschule: 파데르본 공군 학교 // 파데르보너 루프트크리그슐레
  Institut für Luftfahrttechnik: 항공 공학 연구원 // 인스티투트 퓌어 루프트파르트테크닉
  Reichstag: 라이히슈탁 // 제국 의회
  Bundesrat: 분더스라트 // 연방 참의원
  Europarat: 유럽의회 // 오이로파라트
  Europakommission: 유럽 위원회 //  오이로파코미시온

정당은 
  Rote-Armee-Miliz: 적군 민병대 // 로테-아미-밀리츠
  Bewaffneter Gewerkschaftsbund: 무장 노동조합 총연맹 // 바프너터 게베르크샤프츠분트
  Deutsche Organisation der Internationale/Syndikalistische Partei: 인터내셔널 독일 지부/생디칼리스트 당 // 도이체 오르가니자치온 데어 인터나치오날러/진디칼리스티셔 파타이
  Sozialdemokratische Partei Deutschlands: 독일 사회 민주당 // 조치알데모크라티셔 파타이 도이치란츠
  Fortschrittliche Volkspartei: 진보 인민당 // 포르트슈리틀리허 폴크스파타이
  Nationalliberale Partei: 국민 자유당 // 나이초날리베르알러 파타이
  Zentrumspartei: 중앙당 // 젠트룸스파타이
  Deutschkonservative Partei: 독일 보수당 // 도이치콘제르바티페 파타이
  Notstandsregierung: 비상 정권 // 노트슈탄트레기룽
  Deutsche Vaterlandspartei: 독일 조국당 // 도이체 파터란츠파타이
  Kaisertreue Kamarilla: 황제 충성 궁정당 // 카이저트러이어 카마릴라
  Alldeutscher Verband: 범 독일 연맹 // 알도이처 퍼반트

정치 단체는
  Freie Arbeiterunion Deutschland: 독일 자유 노동조합 // 프라이어 아르바이터우니온 도이치란트

기타 단체는
  Halbstarke: 불량 청소년 // 할프슈타크

지명은
  Ludendorfflinie: 루덴도르프 선 // 루덴도르프리니어

직책은
  Reichskanzler: 제국 재상 // 라이히스칸슬러

사건은
  Black Monday: 검은 월요일
  Weltkrieg: 세계대전 // 벨트크리그
  Kaisergipfel: 황제 정상 회담 // 카이저기플

주장은
  Sonderweg: 배제론 // 존더베그

**Comment by skullbe** [comment]
지명 같은 경우, 지크프리트 선도 지크프리트라인이 아닌 지크프리트 선으로 부르니, 루덴도르프 선이 좋을 것같아요. 군/장비관련이 아닌이상 대부분은 직역이 좋다고 봅니다. 현재에도 정당같은 경우 현지발음으로 부르지 않고 완역해서 부르듯이요

**Comment by skullbe** [comment]
아이고 잘못 썼네요 정정합니다. 군이나 무기장비관련 등은 현지발음대로, 나머지는 한국어식으로 완역하는 편이 좋을 것같습니다
국가명은 각각 상황에 따라 토론으로 정하는 것이 좋을 것같습니다

**Comment by skullbe** [comment]
Centroamerica: 센트로아메리카
Federated States of America  : 미주연방
United Provinces of America : 아메리카 연합주
Confederate States of America : 아메리카 연합국
American Union State : 미주연합
Combined Syndicates of America : 아메리카 노동 연맹
Pacific States of America :미 태평양 합중국

이렇게 번역하도록 하겠습니다.
