### ISSUE TITLE
제안: 모드 구조를 바꿨으면 합니다

### ISSUE THREAD

**Issue by kawaialpaca** [skullbe/Kaiserreich-Korean-Translation#744]
지금처럼 카이저라이히 한글패치 모드 안에 카이저라이히 원본모드를 포함하는 방식이 아니라 양쪽을 동시 구동시켜서 적용되는 방식으로 변했으면 합니다.

이렇게 했을때의 장점으로는 
1. 일단 모드가 가벼워집니다. 한글패치 모드의 특성상 업데이트가 자주일어나게 되는데 모드를 경량화한다면 업데이트에 걸리는 시간을 획기적으로 줄일 수 있을 것입니다
2. 원본모드의 업데이트와 시간적 차이를 줄일 수 있습니다. 카라 원본 모드의 대규모 패치가 일어났거나 버그패치를 했을때 한패가 이를 따라가지 못할때가 많았는데 이러면 그럴때 빨리 대처할 수 있을 것입니다

제가 호이 4의 모딩 구조를 확실히 알고 있는 것은 아니지만 (다른 패독사 게임하고 동일하다고 가정하면) 두개 이상의 모드를 같이 사용할때 충돌하는 파일이 있다면 (여기서는 아마 localization 파일들이 되겠지요) 알파벳 순으로 먼저 온 모드의 파일을 우선적으로 읽는 방식으로 적용될 것입니다. 따라서 원본 모드의 이름이 Kaiserreich면 한글패치는 corean language mode- kaiserreich 정도로 이름을 설정하면 둘을 동시에 가동했을때 끊길 일이 없을 것입니다.

**Comment by skullbe** [comment]
카라를 통합시킨 이유  중 하나가 제안하신 2번째 사유입니다.
초기버전에선 한글번역 부분만 집어넣고, 카라와 같이 실행시키는 방식이였는데,
이게 문제가 카라 업데이트 속도와 번역 파일 동기화 속도가 달라서 문제가 생깁니다. 

그래서 모드가 0.7로 업데이트가 됬다면, 번역파일은 그대로 0.6인채가 되버려서, 
당연히 게임은 오류가 나버리는 문제가 생깁니다. 
그래서 번역파일 동기화 속도를 맞추고자 중간에 방식을 변경한 상황입니다.

**Comment by kawaialpaca** [comment]
그런 문제가 있었군요 그렇다면 그냥 대형 패치 이후에 좀 빨리 올려주시는거말고는 방법이 없겠네요
