### ISSUE TITLE
검은 남작의 본명 및 미주 연합 문제 

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#750]
러시아 파일 번역 중에 검은 남작의 본명이 브랑겔과 브란겔 2가지가 사용되던데 통일성이 있어야 할듯 합니다. 이와 비슷하게 미주 연합과 미주 연방 역시 2가지로 사용되고 있더군요

그래서 일단은 두가지 모두 좀 더 번역에 알맞는 기준으로 통일시킬까 하는데 어떤 쪽이 나을까요?

**Comment by kawaialpaca** [comment]
외래어 표기법에 따르면 브란겔쪽이 맞다고 하네요 AUS의 경우 연방쪽이 낫지 않을까 합니다

**Comment by EngineerBeans** [comment]
그러면 일단 검은 남작 쪽은 브란겔로 번역하겠으며 미주 연합 쪽은 좀 더 기다려보겠습니다

**Comment by wintersheart** [comment]
미주 연합은 이미 끝난 문제입니다.
https://github.com/skullbe/Kaiserreich-Korean-Translation/issues/74

**Comment by EngineerBeans** [comment]
그렇다면 현재 AUS 쪽에서 미주 연방이라 쓰여있는건 오류이니 전부 미주 연합으로 변경하겠습니다
