### ISSUE TITLE
Pact의 번역

### ISSUE THREAD

**Issue by EngineerBeans** [skullbe/Kaiserreich-Korean-Translation#857]
현재 Pact가 협약으로 통일되었다고 하는데 General 파일에서는 Pact가 들어간 동맹체의 이름이 ~조약 기구라 쓰여 있던데 오류인건가요? 그리고 제 의견으로는 원문이 Belgrade Pact인데 Warsaw Pact가 바르샤바 조약 기구라 번역된 사례에 따라 Pact는 조약 기구 혹은 조약으로 번역하는게 좀 더 좋을거 같습니다만...또한 Pact의 독일어 버젼인 pakt가 협정이라는 뜻도 있지만 대부분의 독일어에서 조약으로 쓰여(Stahlpakt => 강철 조약의 독일어) 현제 제국 협정 역시 제국 조약으로의 명칭 변경도 같이 제안해봅니다

예시

제국 협정 => 제국 조약

베오그라드 협약 => 베오그라드 조약/베오그라드 조약 기구

카이로 조약 => 카이로 조약/카이로 조약 기구

스칸디나비아 조약 기구 => 스칸디나비아 조약/스칸디나비아 조약 기구

**Comment by kawaialpaca** [comment]
일관되게 조약 기구라는 명칭을 쓰는 쪽에 한 표 던집니다 그 편이 팩션으로서의 느낌을 더 잘 나타내줄 수 있을 것으로 보입니다

**Comment by EngineerBeans** [comment]
그러면 

제국 조약

베오그라드 조약 기구

카이로 조약 기구

스칸디나비아 조약 기구

로 수정하겠습니다

**Comment by khg2202** [comment]
제국 조약보다는 국가 조약 어떨까요?

**Comment by EngineerBeans** [comment]
원문이 Reichspakt인데 Reich이라는 단어 자체가 제국,국가,연방 등 다양한 해석이 가능하지만 게임상 독일이 황제국이고 독일 제국이 Deutsches Reich라는 국명 또한 사용했다는 걸 생각 하면 국가 조약보다는 제국 조약이 훨씬 좋은 표현 같습니다
