### ISSUE TITLE
aspiration society의 번역명은 뭘로 정하는게 좋을까요?

### ISSUE THREAD

**Issue by andares1018** [skullbe/Kaiserreich-Korean-Translation#896]
베트남의 급진 사회주의계열 정당이던 aspiration society 이걸 뭘로 해석하면 좋다고 생각합니까?

열망하는 사회는 누군가가 이미 주장했었던데

하지만 이것의 베트남어 표기를 따라 살펴보니깐 'Hội kín Cao Vọng'로 표기되는데 검색해보니 ''Hội kín'는 비밀조직. 비밀회으로 나온다고 합니다.

그리고 'Cao Vọng'는 높은 야망이라고 나오던데 영어의 'aspiration'의 의미와 비슷할려나 모르겠네요.

그래서 '열망회(熱望會)'로 해석해야하나요 아니면 또다른 다른 명칭으로 해석해야되나요?

https://dict.naver.com/vikodict/vietnamese/#/search?query=Hội kín Cao Vọng

혹시 궁금하실까봐 베트남어 검색 링크도 보여드립니다.

**Comment by gemwon** [comment]
현대의 유럽정당에서는 굳이 **당 등에 의존하지 않는 것을 볼 때 사회의 열망 혹은 열망하는 사회가 낫지 않을까요?

**Comment by andares1018** [comment]
뭐어... 틀린말도 아니기도 하고 딱히 다른 대안이 없으니 열망하는 사회로 하겠습니다.
