### ISSUE TITLE
장비 번역에 대해

### ISSUE THREAD

**Issue by IchGrapemon** [skullbe/Kaiserreich-Korean-Translation#96]
장비의 번역 방침에 대해서 수정이 필요하지 않을까 생각하여 글을 올립니다.

앞서 '일부 국가명에 대하여' 이슈에서 군과 장비의 경우 현지 발음대로 번역하자고 말씀을 해주셨습니다. 현재는 폐기되었습니다만, 어제 독일 장비를 번역할 때 음차하는 것이 적절하지 않다고 생각한 부분이 상당 부분 있었습니다.

그렇게 생각한 이유 중 하나는 해당 장비에 대해서 더 익숙한 표현을 사용하는 것이 좋다고 여겼기 때문이었습니다. 예를 들어 2차 세계 대전 관련 매체에서 Panzerkampfwagen II을 판저캄프바겐 II보다 2호 전차 번역하며 관련 매체를 접한 사람들에게도 2호 전차의 쪽이 더 익숙하다고 보았습니다.

다른 이유는 음차하면 독일어를 모르는 사람의 경우 그 뜻을 파악할 수 없다고 보았기 때문입니다. 예를 들어, 2 cm Flakvierling 38의 경우 2차 세계 대전 관련 매체를 접하신 분이라면 Flak은 대공포라는 것을 알테지만 vierling은 네 쌍둥이, 4연장이라는 의미는 모르실 가능성이 높으며 2차 세계 대전 관련 매체를 접하지 않을 사람이라면 음차시 대공포라는 것도 모를 수 있다고 봤습니다. 

또 다른 이유는 개인적인 이유입니다만, 지난번에 바닐라 호이를 번역할 때 4호 전차 같은 식으로 번역해두었던 것이 판저 4와 같은 식으로 대체된 뒤 채택된 적이 있었기 때문입니다. 제 소견으로는 4호 전차가 판저 4보다 익숙하다고 여겼기 때문에 놀랐었습니다. 그래서 바닐라와 같은 경우를 피하기 위해서 잽싸게 카라의 독일 지상 장비를 번역할 때 장비명의 경우 4호 전차 같이 익숙한 표현이 있으면 익숙한 표현을 사용하는 선에서 완역에 가깝게 진행을 하고자 했습니다.

이렇게 적기는 했기만 저 자신도 방침이 오락가락하여 Kanone을 포가 아닌 카노넨으로 번역하는 등 독일 장비 내에서도 역어의 선정이 중구난방입니다. 

막상 번역을 다 해주신 분도 있어서 함부로 적이 저어합니다만, 장비 번역 방침에 대해 이러한 생각이 들어 몇 자 적어보았습니다.

**Comment by jhtwosun** [comment]
번역을 진행한 사람입니다.

분명히 몇가지 방침이 필요하다고 생각되었습니다. 바닐라 번역에도 번역이 발음대로/완역(직역?)으로 나뉘어져 있어서 어떻게 할지 고민이 들었고, 일단은 바닐라 그대로 가져왔습니다. 

제가 한거라고는 프로그램 돌려서 바닐라에 존재하는 단어들만 카라 파일에 쓴것이고, 그 외에 설명문(desc)파트를 몇가지 번역한것뿐입니다. 

카페에 투표를 올리는것도 한가지 방법이라고 생각됩니다...

**Comment by skullbe** [comment]
jhtwosun님 의견처럼, 카페 한글화토론 게시판에서 투표를 진행해야 될 것같습니다

카라하는 유저들이 더 선호하는 번역이 좋으니까요

**Comment by jhtwosun** [comment]
39분중에 26분이 직역에 투표했습니다. 어떤분이 직역하고 원어 병기하는것이 어떻나고 하셨는데, 어떻게 할까요?

**Comment by IchGrapemon** [comment]
전투장갑차량 4호 전차(캄프판저바겐 피어 혹은 Panzerkampfwagen IV) 이런 식으로요?
