### ISSUE TITLE
Countries/Cosmetic_Countries 번역

### ISSUE THREAD

**Issue by jhtwosun** [skullbe/Kaiserreich-Korean-Translation#98]
Countries 파일의 현재 번역을 보면 (국가)_ADJ 의 번역이 바닐라와 다릅니다.

예를 들어 CAN_totalist_ADJ: 는

- "Canadian"@"캐나다(령)" : 바닐라

- "Canadian"@"캐나다인" : 카라 번역

무엇이 맞는지 몰라서 질문드립니다.

**Comment by skullbe** [comment]
Adj부분은 형용사부분입니다. 그러니까 이벤트등에서 '캐나다인의', '캐나다의' 같이 범용적으로 쓰인다는 것이죠 바닐라에서는 코스메틱태그(영국령 인도제국같은)에서 쓰이는 것으로 착각하고 쓴 것같습니다 그러나 코스매틱태그는 따로 파일이 분리되어있으므로 '캐나다의'혹은 '캐나다인'등으로 번역하는게 좋을 것같습니다
