### ISSUE TITLE
Flanders-Wallonia의 번역명에 관해서

### ISSUE THREAD

**Issue by REDcurrehee** [skullbe/Kaiserreich-Korean-Translation#998]
현재, Flanders-Wallonia의 번역명은 플랑드르-왈로니아(Flandre-Wallonia)라는 프랑스어와 영어가 혼합된 상황인데, 이럴 바에는 차라리 각 지역의 공용어에 맞춰 플란데런-우알로니(Vlaaderen-Wallonie)로 바꾸는 게 어떨까요? 실제로 카이저라이히 원 모드의 각 주 지역 명칭도 플란데런(Vlaanderen)과 우알로니(Wallonie)로 되어 있고 말입니다.

**Comment by kawaialpaca** [comment]
이미 옛날에 플랑드르 왈로니아로 결론 났습니다. 아래쪽에 이미 그 주제로 issue 생성되었습니다. 한번 확인해주세요

**Comment by REDcurrehee** [comment]
확인하고 왔습니다. 하지만, 거기서는 플랑드르-왈로니아가 영어라고 나와 있는데, 플랑드르(Frandre)는 영어가 아닌 프랑스어입니다. 그러므로, 국명이 영어 명칭의 음차로 결정되었다면, 플랑드르-왈로니아(Frandre-Wallonia)가 아닌, 플랜더스-왈로니아(Flanders-Wallonia)로 국명을 바꿔야 한다고 생각합니다.

**Comment by EngineerBeans** [comment]
그러면 계속 말이 나오니 기회에 다시 확실히 정하는게 좋을거 같습니다. 일단 정리를 하자면

1. 영어명에 따른 번역 : 플랜더스-왈로니아

2.각 지역 공영어에 따른 번역 : 플란데런-우알로니

3.현상유지 : 플랑드르-왈로니아

이 3개의 후보 중에서 다시 정하는걸로 합시다 저는 각 지역 공영어에 한편 하겠습니다

**Comment by REDcurrehee** [comment]
저도 플란데런-우알로니를 지지합니다.

**Comment by kawaialpaca** [comment]
분리된다면 모를까 같은 나라에서 서로 다른 언어에서 따온 국가명이 사용된다는것은 옳지 못하다고 봅니다 차라리 영어로 통일해서 플랜더스 - 왈로니아 쪽을 지지합니다

**Comment by EngineerBeans** [comment]
현재 플란데런-우알로니가 2표 플랜더스-왈로니아 1표씩인데 2일 후에도 변동이 없으면 플란데런-우알로니로 번역하겠습니다

**Comment by MADCAT416** [comment]
저도 플란데런-우알로니에 지지표를 보냅니다
